import { z } from "zod";

export const GoalStatusV1 = z.enum(["DRAFT", "AWAITING_CLARIFICATION", "AWAITING_GOAL_CONFIRMATION", "CONFIRMED", "PLANNING", "AWAITING_APPROVAL", "AUTHORIZED", "EXECUTING", "PAUSED", "REAPPROVAL_REQUIRED", "COMPLETED", "FAILED", "CANCELLED"]);
export type GoalStatusV1 = z.infer<typeof GoalStatusV1>;

export const goalTransitionsV1: Readonly<Record<GoalStatusV1, readonly GoalStatusV1[]>> = {
  DRAFT: ["AWAITING_CLARIFICATION", "AWAITING_GOAL_CONFIRMATION", "CANCELLED"], AWAITING_CLARIFICATION: ["AWAITING_GOAL_CONFIRMATION", "CANCELLED"],
  AWAITING_GOAL_CONFIRMATION: ["CONFIRMED", "AWAITING_CLARIFICATION", "CANCELLED"], CONFIRMED: ["PLANNING", "CANCELLED"],
  PLANNING: ["AWAITING_APPROVAL", "FAILED", "CANCELLED"], AWAITING_APPROVAL: ["AUTHORIZED", "REAPPROVAL_REQUIRED", "CANCELLED"],
  AUTHORIZED: ["EXECUTING", "REAPPROVAL_REQUIRED", "CANCELLED"], EXECUTING: ["PAUSED", "REAPPROVAL_REQUIRED", "COMPLETED", "FAILED"],
  PAUSED: ["EXECUTING", "REAPPROVAL_REQUIRED", "FAILED", "CANCELLED"], REAPPROVAL_REQUIRED: ["AWAITING_APPROVAL", "CANCELLED"],
  COMPLETED: [], FAILED: [], CANCELLED: [],
};
export function assertGoalTransition(from: GoalStatusV1, to: GoalStatusV1): void {
  if (!goalTransitionsV1[from].includes(to)) throw new Error(`Invalid goal transition: ${from} -> ${to}`);
}
