import { expect, it } from "vitest";
import { processNextOutboxEvent, type ClaimedOutboxEvent, type OutboxStore } from "./outbox.js";

class MemoryOutboxStore implements OutboxStore {
  event = { id: "event-1", topic: "EXECUTION_COMPLETED", aggregateId: "execution-1", traceId: "trace-1", payload: { ok: true }, attempts: 0, status: "PENDING", claimToken: undefined as string | undefined, claimedAt: undefined as Date | undefined };
  async claimNext(now: Date, leaseMs: number): Promise<ClaimedOutboxEvent | null> { const expired = this.event.status === "PROCESSING" && this.event.claimedAt !== undefined && this.event.claimedAt.getTime() <= now.getTime() - leaseMs; if (this.event.status !== "PENDING" && !expired) return null; this.event.status = "PROCESSING"; this.event.attempts += 1; this.event.claimToken = `claim-${this.event.attempts}`; this.event.claimedAt = now; return { ...this.event, claimToken: this.event.claimToken }; }
  async markPublished(id: string, token: string, publishedAt: Date): Promise<boolean> { void publishedAt; if (id !== this.event.id || token !== this.event.claimToken || this.event.status !== "PROCESSING") return false; this.event.status = "PUBLISHED"; return true; }
  async releaseForRetry(id: string, token: string, error: string): Promise<boolean> { void error; if (id !== this.event.id || token !== this.event.claimToken || this.event.status !== "PROCESSING") return false; this.event.status = "PENDING"; this.event.claimToken = undefined; this.event.claimedAt = undefined; return true; }
}

it("publishes once and preserves trace context", async () => { const store = new MemoryOutboxStore(); const traces: string[] = []; expect(await processNextOutboxEvent(store, { async publish(event) { traces.push(event.traceId); } })).toBe("PUBLISHED"); expect(await processNextOutboxEvent(store, { async publish() {} })).toBe("EMPTY"); expect(traces).toEqual(["trace-1"]); });
it("releases a failed delivery for retry", async () => { const store = new MemoryOutboxStore(); expect(await processNextOutboxEvent(store, { async publish() { throw new Error("offline"); } })).toBe("RETRY"); expect(store.event.status).toBe("PENDING"); expect(await processNextOutboxEvent(store, { async publish() {} })).toBe("PUBLISHED"); expect(store.event.attempts).toBe(2); });
it("reclaims expired leases and rejects the old claim token", async () => { const store = new MemoryOutboxStore(); const first = await store.claimNext(new Date(0), 1_000); expect(await store.claimNext(new Date(500), 1_000)).toBeNull(); const second = await store.claimNext(new Date(1_001), 1_000); expect(second?.claimToken).not.toBe(first?.claimToken); expect(await store.markPublished("event-1", first!.claimToken, new Date())).toBe(false); expect(await store.markPublished("event-1", second!.claimToken, new Date())).toBe(true); });
it("allows only one concurrent claim", async () => { const store = new MemoryOutboxStore(); let deliveries = 0; const publisher = { async publish() { deliveries += 1; } }; await Promise.all([processNextOutboxEvent(store, publisher), processNextOutboxEvent(store, publisher)]); expect(deliveries).toBe(1); });
