import { describe, expect, it } from "vitest";
import { buildApp } from "./app.js";
describe("mock bank", () => {
  it("is healthy", async () => expect((await buildApp().inject({ method: "GET", url: "/health" })).statusCode).toBe(200));
  it("returns string minor units", async () => { const response = await buildApp().inject({ method: "GET", url: "/v1/state/u1" }); expect(response.json().accounts[0].availableMinorUnits).toBe("2000000"); });
  it("returns the active mock scenarios", async () => { const app = buildApp(); await app.inject({ method: "POST", url: "/v1/admin/scenarios/u1", payload: { scenarios: ["ASSET_UNAVAILABLE"] } }); const response = await app.inject({ method: "GET", url: "/v1/admin/scenarios/u1" }); expect(response.json()).toEqual({ scenarios: ["ASSET_UNAVAILABLE"] }); });
  it("does not mutate twice for one key", async () => { const app = buildApp(); const request = { method: "POST" as const, url: "/v1/execute/transfer", headers: { "idempotency-key": "same" }, payload: { userId: "u1", sourceAccountId: "acc-usd", beneficiaryId: "ben-ntu", amount: { currency: "USD", minorUnits: "1000" } } }; const a = await app.inject(request); const b = await app.inject(request); expect(a.json().stateVersion).toBe(b.json().stateVersion); const state = await app.inject({ method: "GET", url: "/v1/state/u1" }); expect(state.json().accounts[1].availableMinorUnits).toBe("499000"); });
  it("rejects a key reused for a different request", async () => { const app = buildApp(); const base = { method: "POST" as const, url: "/v1/execute/transfer", headers: { "idempotency-key": "same" } }; await app.inject({ ...base, payload: { userId: "u1", sourceAccountId: "acc-usd", beneficiaryId: "ben-ntu", amount: { currency: "USD", minorUnits: "1000" } } }); const response = await app.inject({ ...base, payload: { userId: "u1", sourceAccountId: "acc-usd", beneficiaryId: "ben-ntu", amount: { currency: "USD", minorUnits: "2000" } } }); expect(response.statusCode).toBe(409); });
});
